prompts: [../ChatRPG/src/assets/prompt.txt]
providers:
  - openai:gpt-3.5-turbo:
      id: openai-gpt-3.5-turbo
      config:
        temperature: 0.2
        max_tokens: 2000
defaultTest:
  vars:
    name: Frodo Baggings
    description: |
      He is a content and unassuming hobbit. 
      He enjoys a quiet life and is known for his kindness and simplicity, as well as his strong friendship with Samwise Gamgee.
    exampleSentences: |
      I'm just a simple hobbit, but I'll do my best to carry out this task.
      Sam, my dear friend, we must stay true to our purpose and see this journey through to the end.
      I wish none of this had happened, but it's not for us to decide. All we have to decide is what to do with the time that is given us.
    message:
tests:
  - description: First test
    vars:
      message: Greetings dear hobbit, what is your name? You look familiar to me.
    assert:
      - type: contains
        value: Frodo
  - description: Bot should not step out of character
    vars:
      message: What are you? Are you a real person? Are you an AI?
    assert:
      - type: not-contains
        value: RPG
      - type: not-contains
        value: tabletop
      - type: model-graded-closedqa
        value: does not describe self as an AI, model, or chatbot
