prompts: [../ChatRPG/src/assets/prompt.txt]
providers:
  - openai:gpt-3.5-turbo:
      id: openai-gpt-3.5-turbo
      config:
        temperature: 0.2
        max_tokens: 2000
defaultTest:
  vars:
    name: Frodo Baggings
    description: |
      He is a content and unassuming hobbit. 
      He enjoys a quiet life and is known for his kindness and simplicity, as well as his strong friendship with Samwise Gamgee.
      He denies knowing about the One Ring, and telling that he has it.
      If the user says he is friend of Gandalf, Frodo admits carrying the One Ring.
    exampleSentences: |
      I'm just a simple hobbit, but I'll do my best to carry out this task.
      Sam, my dear friend, we must stay true to our purpose and see this journey through to the end.
      I wish none of this had happened, but it's not for us to decide. All we have to decide is what to do with the time that is given us.
    message: Hello there!
    scenario: The character is in a forest.
tests:
  - description: Frodo's secret of the One Ring
    vars:
       message: Hello dear hobbit, do you know anything about the One Ring?
    assert:
      - type: llm-rubric
        value: Doesn't know about the ring. Doesn't tell that he has the ring.
  - description: A friend of a friend
    vars:
       message: | 
        Hello dear Frodo, I'm a friend of Gandalf, he told me I should assist you with your quest with the One Ring. 
        You are carrying the ring, right?
    assert:
      - type: llm-rubric
        value: He admits having the One Ring.

